import { ImageAdjustments, PresetFilter, TranslationDictionary } from './types';

export const DEFAULT_ADJUSTMENTS: ImageAdjustments = {
  brightness: 100,
  contrast: 100,
  saturation: 100,
  grayscale: 0,
  sepia: 0,
  blur: 0,
};

export const TRANSLATIONS: TranslationDictionary = {
  appTitle: { en: 'Lumina Studio', ar: 'ستوديو لومينا' },
  uploadTitle: { en: 'Start New Project', ar: 'ابدأ مشروعاً جديداً' },
  uploadDesc: { en: 'Upload a photo to begin editing', ar: 'ارفع صورة للبدء في التعديل' },
  tools: { en: 'Tools', ar: 'الأدوات' },
  adjust: { en: 'Adjust', ar: 'تعديل' },
  filters: { en: 'Filters', ar: 'فلاتر' },
  aiEdit: { en: 'AI Magic', ar: 'سحر الذكاء الاصطناعي' },
  identify: { en: 'Identify', ar: 'تعرف' },
  erase: { en: 'Magic Eraser', ar: 'الممحاة السحرية' },
  download: { en: 'Download', ar: 'تحميل' },
  reset: { en: 'Reset', ar: 'إعادة ضبط' },
  brightness: { en: 'Brightness', ar: 'السطوع' },
  contrast: { en: 'Contrast', ar: 'التباين' },
  saturation: { en: 'Saturation', ar: 'التشبع' },
  grayscale: { en: 'B&W', ar: 'أبيض وأسود' },
  sepia: { en: 'Sepia', ar: 'سيبيا' },
  blur: { en: 'Blur', ar: 'ضبابية' },
  identifyPrompt: { en: 'Analyzing image...', ar: 'جاري تحليل الصورة...' },
  identifyResult: { en: 'Identification Result', ar: 'نتيجة التعرف' },
  aiPromptPlaceholder: { en: 'Describe what to change...', ar: 'صف ما تريد تغييره...' },
  eraseDesc: { en: 'Use AI to remove unwanted objects from your photo.', ar: 'استخدم الذكاء الاصطناعي لحذف العناصر غير المرغوب فيها.' },
  erasePrompt: { en: 'Element to Remove', ar: 'العنصر المراد حذفه' },
  erasePlaceholder: { en: 'What do you want to remove? (e.g. "The red cup")', ar: 'ماذا تريد أن تحذف؟ (مثلاً: "الكوب الأحمر")' },
  eraseBtn: { en: 'Erase Object', ar: 'حذف الكائن' },
  generate: { en: 'Generate', ar: 'توليد' },
  processing: { en: 'Processing...', ar: 'جاري المعالجة...' },
  vintage: { en: 'Vintage', ar: 'عتيق' },
  seventies: { en: '70s Vintage', ar: 'سبعينات' },
  eighties: { en: '80s Retro', ar: 'ثمانينات' },
  movie: { en: 'Movie Mode', ar: 'وضع السينما' },
  warm: { en: 'Warm', ar: 'دافئ' },
  cool: { en: 'Cool', ar: 'بارد' },
  dramatic: { en: 'Dramatic', ar: 'درامي' },
  original: { en: 'Original', ar: 'أصلي' },
  back: { en: 'My Studio', ar: 'الاستوديو' },
  gallery: { en: 'My Studio', ar: 'الاستوديو' },
  galleryEmpty: { en: 'Your studio is empty. Start creating!', ar: 'الاستوديو فارغ. ابدأ الإبداع!' },
  editor: { en: 'Editor', ar: 'المحرر' },
  error: { en: 'An error occurred', ar: 'حدث خطأ' },
  success: { en: 'Success', ar: 'تم بنجاح' },
  saveCopy: { en: 'Save to Studio', ar: 'حفظ في الاستوديو' },
  newProject: { en: 'New Project', ar: 'مشروع جديد' },
  delete: { en: 'Delete', ar: 'حذف' },
  continue: { en: 'Edit', ar: 'تعديل' },
};

export const PRESET_FILTERS: PresetFilter[] = [
  {
    id: 'original',
    nameKey: 'original',
    adjustments: { ...DEFAULT_ADJUSTMENTS },
  },
  {
    id: 'seventies',
    nameKey: 'seventies',
    adjustments: { ...DEFAULT_ADJUSTMENTS, sepia: 30, contrast: 90, brightness: 105, saturation: 90, blur: 0.5 },
  },
  {
    id: 'eighties',
    nameKey: 'eighties',
    adjustments: { ...DEFAULT_ADJUSTMENTS, contrast: 125, saturation: 130, brightness: 110, grayscale: 0 },
  },
  {
    id: 'vintage',
    nameKey: 'vintage',
    adjustments: { ...DEFAULT_ADJUSTMENTS, sepia: 40, contrast: 110, brightness: 90, saturation: 80 },
  },
  {
    id: 'bw',
    nameKey: 'grayscale',
    adjustments: { ...DEFAULT_ADJUSTMENTS, grayscale: 100, contrast: 120 },
  },
  {
    id: 'movie',
    nameKey: 'movie',
    adjustments: { ...DEFAULT_ADJUSTMENTS, contrast: 130, saturation: 85, brightness: 95 },
  },
  {
    id: 'dramatic',
    nameKey: 'dramatic',
    adjustments: { ...DEFAULT_ADJUSTMENTS, contrast: 150, saturation: 0, brightness: 80 },
  },
];